---
title: "Day 1.1 Data cleaning"
author: "Catherine Kim"
date: "`r Sys.Date()`"
categories: ["R"]
tags: ["dplyr"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Centre for Biodiversity and Conservation Science + Library R workshop
# Day1

## Prequesites

This R workshop assumes basic knowledge of R including:

* Installing and loading packages
* How to read in data
    + read.csv
    + read_csv
    + and similar
* Creating objects in R
    

# Data manipulation

## Read in the data

```{r read data}

```

# Including Plots

You can also embed plots. See Figure \@ref(fig:pie) for example:

```{r pie, fig.cap='A fancy pie chart.', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

```{r}
summary(Orange)
```

```{r echo=FALSE}
library(ggplot2)
ggplot(Orange, aes(x = age, 
                   y = circumference, 
                   color = Tree)) +
  geom_point() +
  geom_line() +
  guides(color = FALSE) +
  theme_bw()
```